#!/usr/bin/env bash

function bash_multi() {
    bash_multi_cleanup() {
        unset -f bash_multi_cleanup
        unset -f bash_multi_usage
    }

    bash_multi_usage() {
        echo "Usage: bash_multi [OPTIONS]"
        echo "Options:"
        echo "    -f, --flag"
        echo "        Example flag"
        echo "    -f, --flag=FLAG"
        echo "        Example for storing cli arg"
        echo "    -h, --help"
        echo "        Display this help message"
        echo
        bash_multi_cleanup
    }

    declare -a args
    unset flag

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--") shift && args+=("$@") && break ;;
            "-f"|"--flag") flag="true" ;;
            "-f"|"--flag") shift; [[ $# -gt 0 ]] || usage 1
                flag="--flag $1"
                ;;
            "-h"|"--help") bash_multi_usage; return 0 ;;
            *) args+=("$1") ;;
        esac
        shift
    done
    [[ -z ${args[@]} ]] || set -- "${args[@]}"

    [[ $# -eq 0 ]] && bash_multi_usage && return 1

    for arg in "$@"; do echo "$arg"; done

    bash_multi_cleanup
}

if [[ -n ${BASH_SOURCE[0]} ]]; then
    case "$0" in
        *"bash") ;;
        *) bash_multi "$@" ;;
    esac
fi
