#!/usr/bin/env bash

function bash_multi() {
    for dep in TODO; do
        if [[ -z $(command -v $dep) ]]; then
            echo "$dep is not installed"
            return 3
        fi
    done; unset dep

    bash_multi_cleanup() {
        unset args flag help store
        unset -f bash_multi_cleanup bash_multi_usage
    }

    bash_multi_usage() {
        cat <<EOF
Usage: bash_multi [OPTIONS]

TODO

Options:
    -h, --help         Display this help message
    -t, --todo         Example flag
    -t, --todo=TODO    Example for storing cli arg

EOF
        bash_multi_cleanup
    }

    declare -a args
    unset help todo

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--") shift && args+=("$@") && break ;;
            "-h"|"--help") help="true" ;;
            "-t"|"--todo") todo="true" ;;
            "-t"|"--todo"*)
                case "$1" in
                    "--"*"="*)
                        arg="${1#*=}"
                        [[ -z $arg ]] && bash_multi_usage && return 1
                        ;;
                    *)
                        shift
                        [[ $# -eq 0 ]] && bash_multi_usage && return 1
                        arg="$1"
                        ;;
                esac
                todo="$arg"
                ;;
            *) args+=("$1") ;;
        esac
        shift
    done
    [[ -z ${args[@]} ]] || set -- "${args[@]}"

    [[ -n $help ]] && bash_multi_usage && return 0
    [[ $# -eq 0 ]] && bash_multi_usage && return 2

    for arg in "$@"; do echo "$arg"; done

    bash_multi_cleanup
}

if [[ -n ${BASH_SOURCE[0]} ]]; then
    case "$0" in
        *"bash") ;;
        *) bash_multi "$@" ;;
    esac
fi
