#!/usr/bin/env bash

set -o noglob

clean() {
    [[ ${1:-0} -ne 0 ]] || [[ ! -d $cache ]] || rm -rf $cache
    [[ -z $script ]] || [[ ! -f $script ]] || rm -f $script
    echo -en "\e[?25h" # Show cursor again
    exit ${1:-0}
}

err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }

errx() { echo -e "${color:+\e[31m}[!] ${@:2}\e[0m"; clean $1; }

good() { echo -e "${color:+\e[32m}[+] $@\e[0m"; }

info() { echo -e "${color:+\e[37m}[*] $@\e[0m"; }

json_get() {
    [[ -z $json ]] || jq -cr ".$@" $json | sed -r "s/^null$//g"
}

long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}

# TODO
read_resume_file() { echo -n; }

subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }

usage() {
    echo "Usage: ${0##*/} [OPTIONS] <arg1>... [argN]"
    echo
    echo "TODO"
    echo
    echo "Options:"
    echo "    -f, --flag           Example flag"
    echo "    -h, --help           Display this help message"
    echo "    --nocolor            Disable colorized output"
    echo "    -r, --resume         Resume from a previous run"
    echo "    -s, --store=VAL      Example for storing cli arg"
    echo "    -t, --threads=NUM    Use the specied number of threads"
    echo "                         (default: $threads)"
    echo "    -v, --verbose        Do not hide parallel errors"
    echo
    exit $1
}

warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }

# TODO
write_resume_file() {
    cat >$json <<EOF
{}
EOF
}

declare -a args
unset flag help store
cache="${0##*/}.resume"
color="true"
joblog="$cache/joblog.txt"
json="$cache/${0##*/}.json"
parallel="true"
threads="32"

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-f"|"--flag") flag="true" ;;
        "-h"|"--help") help="true" ;;
        "--nocolor") unset color ;;
        "-r"|"--resume") resume="--resume" ;;
        "-s"|"--store"*) store="$(long_opt $@)" || shift ;;
        "-t"|"--threads"*) threads="$(long_opt $@)" || shift ;;
        "-v"|"--verbose") verbose="true" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

# Check for valid params and missing dependencies
[[ -z $help ]] || usage 0
[[ $# -gt 0 ]] || [[ -n $resume ]] || usage 2
# for dep in TODO; do
#     [[ -n $(command -v $dep) ]] || errx 3 "$dep is not installed"
# done; unset dep

# Determine parallel situation
if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
    warn "Parallel is not installed, defaulting to single-threaded"
    unset parallel
fi

# Cite if needed
if [[ -n $parallel ]] && [[ ! -f $HOME/.parallel/will-cite ]]; then
    mkdir -p $HOME/.parallel
    parallel --citation
fi

if [[ -n $parallel ]]; then
    # Ensure resume directory exists
    mkdir -p $cache

    # Check for resume file
    if [[ -f $json ]] && [[ -z $resume ]]; then
        warn "Resume file found" >&2
        while :; do
            # Prompt whether to overwrite or resume
            read -n 1 -p "Would you like to resume [y/n/q]: " -s ans
            echo

            case "$ans" in
                "n") write_resume_file; break ;;
                "q") exit 0 ;;
                "y") read_resume_file; resume="--resume"; break ;;
                *) echo "Invalid response, try again!" ;;
            esac
        done
    elif [[ -f $json ]]; then
        read_resume_file
    elif [[ -n $resume ]]; then
        errx 6 "No resume file found in current directory"
    else
        write_resume_file
    fi
fi

# Dataset used by parallel
dataset="$cache/${0##*/}.dataset"

# Script used by parallel
script="/tmp/${0##*/}.parallel"

# Ensure cleanup on ^C
trap "clean -1" SIGINT

# Hide cursor
echo -en "\e[?25l"

# Process dataset
info "Processing dataset for jobs"

if [[ ! -f $dataset ]]; then
    total="0"
    for data in "$@"; do
        ((total += 1))
        echo "$data" >>$dataset
    done; unset data
else
    total="$(cat $dataset | wc -l)"
fi
[[ $total -ne 0 ]] || errx 4 "No dataset provided"

subinfo "$total jobs to run"

# Create sub-script
cat >$script <<EOF
#!/usr/bin/env bash

set -o noglob

err() { echo -e "\r${color:+\e[31m}[!] \$@\e[0m\e[K"; }

errx() { echo -e "\r${color:+\e[31m}[!] \${@:2}\e[0m\e[K"; exit \$1; }

good() { echo -e "\r${color:+\e[32m}[+] \$@\e[0m\e[K"; }

info() { echo -e "\r${color:+\e[37m}[*] \$@\e[0m\e[K"; }

subinfo() { echo -e "\r${color:+\e[36m}[=] \$@\e[0m\e[K"; }

warn() { echo -e "\r${color:+\e[33m}[-] \$@\e[0m\e[K"; }

# TODO
timeout="\$((RANDOM % 4))"
sleep \$timeout
good "\$1"
EOF
chmod 700 $script

# Run sub-script
if [[ -n $parallel ]]; then
    # If more than one dataset, cat and pipe to parallel
    parallel -a $dataset --bar --joblog ${resume:++}$joblog --lb \
        -P $threads -r $resume $script {}
    [[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2
else
    count="1"
    while read -r data; do
        echo -e "\r\e[K" >&2
        echo -en "${color:+\e[37m}[$count/$total]\e[0m\e[K\e[1A" >&2
        $script "$data"
        ((count += 1))
    done <$dataset; unset data
fi

clean
