#!/usr/bin/env bash

# Default group (user:1000)
gid="${DKR_GID:-1000}"
gname="${DKR_GNAME:-user}"

# Default user (user:1000)
uid="${DKR_UID:-1000}"
uname="${DKR_UNAME:-user}"

# Does user with UID already exist?
old_uid="$(id -nu "$uid" 2>/dev/null)"

# If root or UID of 0 provided, just run command
if [[ $(id -u) -ne 0 ]] || [[ $uid -eq 0 ]]; then
    exec "$@"
fi

# Create group if it doesn't exist
groupadd -f "$gname"
groupmod -g "$gid" -o "$gname" 2>/dev/null

# Create user if they don't exist
if [[ -z $old_uid ]]; then
    useradd -d /home/user -g "$gid" -mou "$uid" "$uname" 2>/dev/null
else
    usermod -d /home/user -g "$gid" -l "$uname" -m "$old_uid" \
        2>/dev/null
fi
chown -R "$uname":"$gname" /home/user

# Sudo (a few different ways)
groupadd -f sudo
groupadd -f wheel
usermod -a -G sudo,wheel "$uname"
mkdir -p /etc/sudoers.d
echo "$uname ALL=(ALL) NOPASSWD: ALL" >"/etc/sudoers.d/$uname"

# Store cmd
cmd="$*"
[[ -n $cmd ]] || cmd="$(command -v bash)"
[[ -n $cmd ]] || cmd="sh"

# Run command as specified user
export HOME="/home/user"
export USER="user"

if [[ -n $(command -v sudo) ]]; then
    sudo -E -u "$uname" $cmd
else
    su -c "$cmd" -m "$uname"
fi
