#!/usr/bin/env python3

import argparse
import sys

def main(cli):
    print(cli.t)
    print(cli.todo)
    print(cli.arg1)

def parse():
    parser = argparse.ArgumentParser(
        add_help=False,
        description="TODO",
        usage=sys.argv[0] + " [OPTIONS] [todo]"
    )
    parser.add_argument(
        "-h",
        "--help",
        action="store_true",
        help="Display this help message"
    )
    parser.add_argument(
        "-t",
        action="store_true",
        help="Example short flag"
    )
    parser.add_argument(
        "--todo",
        help="Example long flag"
    )
    parser.add_argument(
        "arg1",
        help="Optional argument",
        metavar="arg1",
        nargs="?"
    )
    cli = parser.parse_args()

    if (cli.help):
        parser.print_help()
        sys.exit(0)

    return cli

if __name__ == "__main__":
    cli = parse()
    main(cli)
